"""initial migration

Revision ID: cb328c7b28b4
Revises: 
Create Date: 2025-08-07 20:53:36.398100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb328c7b28b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='scriptstatus'), nullable=False),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='加密密码'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.Text(), nullable=True, comment='头像URL'),
    sa.Column('bio', sa.Text(), nullable=True, comment='个人简介'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='是否已验证邮箱'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='是否管理员'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('background_stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('setting_description', sa.Text(), nullable=True),
    sa.Column('incident_description', sa.Text(), nullable=True),
    sa.Column('victim_background', sa.Text(), nullable=True),
    sa.Column('investigation_scope', sa.Text(), nullable=True),
    sa.Column('rules_reminder', sa.Text(), nullable=True),
    sa.Column('murder_method', sa.String(length=100), nullable=True),
    sa.Column('murder_location', sa.String(length=255), nullable=True),
    sa.Column('discovery_time', sa.String(length=100), nullable=True),
    sa.Column('victory_conditions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('secret', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('is_murderer', sa.Boolean(), nullable=True),
    sa.Column('is_victim', sa.Boolean(), nullable=True),
    sa.Column('personality_traits', sa.JSON(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('voice_preference', sa.String(length=50), nullable=True),
    sa.Column('voice_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_to', sa.String(length=100), nullable=True),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.Enum('PHYSICAL', 'DOCUMENT', 'VIDEO', 'AUDIO', 'IMAGE', name='evidencetype'), nullable=True),
    sa.Column('importance', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_phases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('BACKGROUND', 'INTRODUCTION', 'EVIDENCE_COLLECTION', 'INVESTIGATION', 'DISCUSSION', 'VOTING', 'REVELATION', 'ENDED', name='gamephaseenum'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('session_id', sa.String(length=100), nullable=False, comment='会话ID'),
    sa.Column('script_id', sa.Integer(), nullable=False, comment='剧本ID'),
    sa.Column('host_user_id', sa.Integer(), nullable=False, comment='房主用户ID'),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'ENDED','PAUSED', 'CANCELED', name='gamesessionstatus'), nullable=False, comment='游戏会话状态'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='游戏开始时间'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='游戏结束时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_session_id'), 'game_sessions', ['session_id'], unique=True)
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False, comment='图片ID'),
    sa.Column('image_type', sa.Enum('COVER', 'CHARACTER', 'EVIDENCE', 'SCENE', name='imagetype'), nullable=False, comment='图片类型'),
    sa.Column('url', sa.Text(), nullable=False, comment='图片URL'),
    sa.Column('path', sa.Text(), nullable=True, comment='图片存储路径'),
    sa.Column('script_id', sa.Integer(), nullable=False, comment='剧本ID'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作者ID'),
    sa.Column('positive_prompt', sa.Text(), nullable=True, comment='正向提示词'),
    sa.Column('negative_prompt', sa.Text(), nullable=True, comment='负向提示词'),
    sa.Column('width', sa.String(length=10), nullable=True, comment='图片宽度'),
    sa.Column('height', sa.String(length=10), nullable=True, comment='图片高度'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('searchable_items', sa.JSON(), nullable=True),
    sa.Column('background_image_url', sa.Text(), nullable=True),
    sa.Column('is_crime_scene', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_events',
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tts_file_url', sa.String(length=500), nullable=True),
    sa.Column('tts_voice', sa.String(length=50), nullable=True),
    sa.Column('tts_duration', sa.Float(), nullable=True),
    sa.Column('tts_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'SKIPPED', name='ttsgeneratedstatus'), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_events_character_name'), 'game_events', ['character_name'], unique=False)
    op.create_index(op.f('ix_game_events_event_type'), 'game_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_game_events_session_id'), 'game_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_game_events_timestamp'), 'game_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_events_timestamp'), table_name='game_events')
    op.drop_index(op.f('ix_game_events_session_id'), table_name='game_events')
    op.drop_index(op.f('ix_game_events_event_type'), table_name='game_events')
    op.drop_index(op.f('ix_game_events_character_name'), table_name='game_events')
    op.drop_table('game_events')
    op.drop_table('locations')
    op.drop_table('images')
    op.drop_index(op.f('ix_game_sessions_session_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_table('game_phases')
    op.drop_table('evidence')
    op.drop_table('characters')
    op.drop_table('background_stories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scripts')
    # ### end Alembic commands ###