"""add game session total times

Revision ID: cc0436694e36
Revises: a1b2c3d4e5f6
Create Date: 2025-08-10 22:04:43.788317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0436694e36'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_game_events_public'), table_name='game_events')
    op.drop_index(op.f('idx_game_events_session_character'), table_name='game_events')
    op.drop_index(op.f('idx_game_events_session_type'), table_name='game_events')
    op.drop_index(op.f('idx_game_events_tts_status'), table_name='game_events')
    op.drop_index(op.f('idx_game_events_session_timestamp'), table_name='game_events')
    op.create_index('idx_game_events_session_timestamp', 'game_events', ['session_id', 'timestamp'], unique=False)
    op.add_column('game_sessions', sa.Column('total_tts_duration', sa.Float(), nullable=True, comment='累计TTS音频时长（秒）'))
    op.drop_index(op.f('idx_game_sessions_script_time'), table_name='game_sessions')
    op.drop_index(op.f('idx_game_sessions_status_time'), table_name='game_sessions')
    op.drop_index(op.f('idx_game_sessions_user_status_time'), table_name='game_sessions')
    op.create_index('idx_game_sessions_host_user_id', 'game_sessions', ['host_user_id'], unique=False)
    op.create_index('idx_game_sessions_script_id', 'game_sessions', ['script_id'], unique=False)
    op.create_index('idx_game_sessions_status', 'game_sessions', ['status'], unique=False)
    op.alter_column('user_game_participants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_user_game_participants_session'), table_name='user_game_participants')
    op.drop_index(op.f('idx_user_game_participants_user'), table_name='user_game_participants')
    op.drop_constraint(op.f('uq_user_game_participant_session_user'), 'user_game_participants', type_='unique')
    op.create_index(op.f('ix_user_game_participants_session_id'), 'user_game_participants', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_game_participants_user_id'), 'user_game_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_game_participants_user_id'), table_name='user_game_participants')
    op.drop_index(op.f('ix_user_game_participants_session_id'), table_name='user_game_participants')
    op.create_unique_constraint(op.f('uq_user_game_participant_session_user'), 'user_game_participants', ['session_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_game_participants_user'), 'user_game_participants', ['user_id', 'joined_at'], unique=False)
    op.create_index(op.f('idx_user_game_participants_session'), 'user_game_participants', ['session_id', 'is_active'], unique=False)
    op.alter_column('user_game_participants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_game_sessions_status', table_name='game_sessions')
    op.drop_index('idx_game_sessions_script_id', table_name='game_sessions')
    op.drop_index('idx_game_sessions_host_user_id', table_name='game_sessions')
    op.create_index(op.f('idx_game_sessions_user_status_time'), 'game_sessions', ['host_user_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_game_sessions_status_time'), 'game_sessions', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_game_sessions_script_time'), 'game_sessions', ['script_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('game_sessions', 'total_tts_duration')
    op.drop_index('idx_game_events_session_timestamp', table_name='game_events')
    op.create_index(op.f('idx_game_events_session_timestamp'), 'game_events', ['session_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_game_events_tts_status'), 'game_events', ['session_id', 'tts_status'], unique=False)
    op.create_index(op.f('idx_game_events_session_type'), 'game_events', ['session_id', 'event_type', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_game_events_session_character'), 'game_events', ['session_id', 'character_name', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_game_events_public'), 'game_events', ['session_id', 'is_public', sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###